BEGIN;
CREATE TEMP TABLE lead_fixture(sender uuid,receiver uuid,stranger uuid,sid uuid,receiver_sid uuid,freela bigint,request uuid);
GRANT SELECT ON lead_fixture TO authenticated;
INSERT INTO lead_fixture VALUES(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),NULL,gen_random_uuid());
INSERT INTO auth.users(id,email,email_confirmed_at,role,aud) SELECT u,u||'@example.invalid',now(),'authenticated','authenticated' FROM lead_fixture f CROSS JOIN LATERAL unnest(ARRAY[f.sender,f.receiver,f.stranger]) u;
INSERT INTO auth.sessions(id,user_id,created_at,updated_at) SELECT sid,sender,now(),now() FROM lead_fixture UNION ALL SELECT receiver_sid,receiver,now(),now() FROM lead_fixture;
WITH f AS(INSERT INTO public.freelancers_sugeridos(nome,categoria,bio,aprovado) VALUES('__isolated_link_test__','Estratégia','Teste revertido de roteamento de pedidos',true) RETURNING id) UPDATE lead_fixture SET freela=f.id FROM f;
INSERT INTO crm_private.freelancer_owners SELECT freela,receiver FROM lead_fixture;
SELECT set_config('request.jwt.claims',(SELECT jsonb_build_object('sub',sender,'session_id',sid,'role','authenticated')::text FROM lead_fixture),true);
SET LOCAL ROLE authenticated;
DO $$ DECLARE f record; n int; BEGIN SELECT * INTO f FROM lead_fixture;
 INSERT INTO public.crm_freelancer_requests(id,freelancer_id,title,brief,contact) VALUES(f.request,f.freela,'Projeto de CRM','Preciso de apoio em um projeto de CRM para minha equipe','contato@example.invalid');
 ASSERT EXISTS(SELECT 1 FROM public.crm_freelancer_requests WHERE id=f.request AND recipient_id=f.receiver),'Wrong receiver';
 BEGIN INSERT INTO public.crm_freelancer_requests(id,freelancer_id,title,brief,contact) VALUES(gen_random_uuid(),f.freela,'Projeto de CRM','Preciso de apoio em um projeto de CRM para minha equipe','contato@example.invalid');RAISE EXCEPTION 'Duplicate accepted';EXCEPTION WHEN unique_violation THEN NULL; END;
 BEGIN INSERT INTO public.crm_freelancer_requests(id,freelancer_id,recipient_id,title,brief,contact) VALUES(gen_random_uuid(),f.freela,f.stranger,'Outro projeto','Descrição de teste de roteamento privado','contato@example.invalid');RAISE EXCEPTION 'Forged recipient accepted';EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 UPDATE public.crm_freelancer_requests SET status='won' WHERE id=f.request;GET DIAGNOSTICS n=ROW_COUNT;ASSERT n=0,'Sender changed receiver progress';
 INSERT INTO public.crm_freelancer_claims(freelancer_id,evidence) VALUES(f.freela,'Contato profissional para confirmar minha identidade');
 UPDATE public.crm_freelancer_claims SET status='approved' WHERE freelancer_id=f.freela;GET DIAGNOSTICS n=ROW_COUNT;ASSERT n=0,'Self-approved claim';
 ASSERT public.crm_submission_status()->>'used'='2','Duplicate consumed quota';
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',f.receiver,'session_id',f.receiver_sid,'role','authenticated')::text,true);
 ASSERT EXISTS(SELECT 1 FROM public.crm_freelancer_requests WHERE id=f.request),'Receiver cannot see lead';
 UPDATE public.crm_freelancer_requests SET status='contact' WHERE id=f.request;GET DIAGNOSTICS n=ROW_COUNT;ASSERT n=1,'Receiver cannot progress lead';
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',f.stranger,'role','authenticated')::text,true);
 ASSERT NOT EXISTS(SELECT 1 FROM public.crm_freelancer_requests WHERE id=f.request),'Stranger reads private lead';
 ASSERT NOT EXISTS(SELECT 1 FROM public.crm_freelancer_claims WHERE freelancer_id=f.freela),'Stranger reads ownership evidence';
END $$;
RESET ROLE;
SET LOCAL ROLE anon;
DO $$ BEGIN
 BEGIN PERFORM 1 FROM public.crm_freelancer_requests;RAISE EXCEPTION 'Anonymous lead read';EXCEPTION WHEN insufficient_privilege THEN NULL;END;
 ASSERT NOT EXISTS(SELECT id FROM public.crm_partner_communities WHERE status<>'approved'),'Pending partner public';
END $$;
RESET ROLE;
SELECT 'PASS: exact recipient routing, duplicate and recipient forgery rejection, owner-only lead progression, claim self-approval denied, privacy and public partner moderation. Rolled back.' result;
ROLLBACK;
