BEGIN;
CREATE TEMP TABLE fixture(uid uuid,sid uuid,other_uid uuid,deal uuid);
GRANT ALL ON fixture TO authenticated,anon;
INSERT INTO fixture VALUES(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid());
INSERT INTO auth.users(id,email,email_confirmed_at,role,aud) SELECT uid,'workspace-'||uid||'@example.invalid',now(),'authenticated','authenticated' FROM fixture UNION ALL SELECT other_uid,'workspace-'||other_uid||'@example.invalid',now(),'authenticated','authenticated' FROM fixture;
INSERT INTO auth.sessions(id,user_id,created_at,updated_at) SELECT sid,uid,now(),now() FROM fixture;
SELECT set_config('request.jwt.claims',(SELECT jsonb_build_object('sub',uid,'session_id',sid,'role','authenticated')::text FROM fixture),true);
SET LOCAL ROLE authenticated;
DO $$ DECLARE f record; n int; BEGIN
 SELECT * INTO f FROM fixture;
 INSERT INTO public.crm_consultant_deals(id,title,status,payload) VALUES(f.deal,'Verificação isolada','lead','{"value":1000}');
 UPDATE public.crm_consultant_deals SET status='contact' WHERE id=f.deal;
 ASSERT (SELECT count(*) FROM public.crm_consultant_deals WHERE id=f.deal)=1,'Edit duplicated deal';
 ASSERT public.crm_submission_status()->>'used'='1','Edit consumed new submission';
 BEGIN INSERT INTO public.crm_consultant_deals(id,title,status) VALUES(f.deal,'Reenvio','lead'); RAISE EXCEPTION 'Duplicate accepted'; EXCEPTION WHEN unique_violation THEN NULL; END;
 BEGIN INSERT INTO public.crm_consultant_deals(owner_id,title,status) VALUES(f.other_uid,'Invalid owner','lead'); RAISE EXCEPTION 'Forged owner accepted'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 BEGIN UPDATE public.crm_consultant_deals SET owner_id=f.other_uid WHERE id=f.deal; RAISE EXCEPTION 'Owner reassignment accepted'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 INSERT INTO public.crm_consultant_tasks(title,status) VALUES('Tarefa isolada','pending');
 INSERT INTO public.crm_consultant_proposals(title,status,payload) VALUES('Proposta isolada','draft','{"scope":"Teste sem publicação"}');
 INSERT INTO public.crm_consultant_contracts(title,status) VALUES('Rascunho isolado','draft');
 BEGIN INSERT INTO public.crm_partner_communities(title,description,url,status) VALUES('Comunidade isolada','Descrição de teste isolado','https://example.invalid/test','approved'); RAISE EXCEPTION 'Self approval accepted'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
 INSERT INTO public.crm_partner_communities(title,description,url) VALUES('Comunidade isolada','Descrição de teste isolado','https://example.invalid/test');
 ASSERT public.crm_submission_status()->>'used'='5','Global count mismatch';
 UPDATE public.crm_partner_communities SET status='approved' WHERE url='https://example.invalid/test';GET DIAGNOSTICS n=ROW_COUNT;ASSERT n=0,'Owner approved own suggestion';
 BEGIN INSERT INTO public.crm_consultant_tasks(title,status) VALUES('Sexto envio','pending'); RAISE EXCEPTION 'Sixth write accepted'; EXCEPTION WHEN SQLSTATE 'P0001' THEN IF SQLERRM NOT LIKE 'Limite de 5%' THEN RAISE;END IF; END;
 PERFORM set_config('request.jwt.claims',jsonb_build_object('sub',f.other_uid,'role','authenticated')::text,true);
 ASSERT NOT EXISTS(SELECT 1 FROM public.crm_consultant_deals WHERE id=f.deal),'Other account sees private deal';
 ASSERT NOT EXISTS(SELECT 1 FROM public.crm_partner_communities WHERE url='https://example.invalid/test'),'Pending partner public';
 UPDATE public.crm_consultant_deals SET title='Unwanted change' WHERE id=f.deal;GET DIAGNOSTICS n=ROW_COUNT;ASSERT n=0,'Other account changed deal';
 DELETE FROM public.crm_consultant_deals WHERE id=f.deal;GET DIAGNOSTICS n=ROW_COUNT;ASSERT n=0,'Other account deleted deal';
 BEGIN INSERT INTO public.crm_consultant_tasks(title,status) VALUES('Sem sessão','pending'); RAISE EXCEPTION 'No session accepted'; EXCEPTION WHEN insufficient_privilege THEN NULL; END;
END $$;
RESET ROLE;
SET LOCAL ROLE anon;
DO $$ BEGIN BEGIN PERFORM 1 FROM public.crm_consultant_deals; RAISE EXCEPTION 'Anonymous read accepted'; EXCEPTION WHEN insufficient_privilege THEN NULL; END; END $$;
RESET ROLE;
SELECT 'PASS: five modules persist; updates do not duplicate; retry ID unique; ownership and anonymous/session restrictions; pending moderation; global sixth submission blocked. All fixtures rolled back.' AS result;
ROLLBACK;
